nytimes/react-tracking

README.md, build/dispatchTrackingEvent.js, package.json, src/__tests__/dispatchTrackingEvent.test.js, src/__tests__/e2e.test.js, src/dispatchTrackingEvent.js, yarn.lock
Replaces default `dispatch()` behavior of calling CustomEvent to instead push to `window.dataLayer[]` which is a good default for most apps that use Google Tag Manager.
This should be the final breaking change for a while, hopefully! It's also the last item before open sourcing the project 🎉 
Closes #26
=> Remove default CustomEvent dispatcher (v4.0.0)

README.md, src/__tests__/e2e.test.js, src/__tests__/trackEventMethodDecorator.test.js, src/trackEventMethodDecorator.js
Hiii 👋 
We've been very excited to integrate react-tracking into [our](https://github.com/artsy/reaction) [work](https://github.com/artsy/emission) over at [Artsy](https://www.artsy.net/)!
In our use of the library, we came the need to access the component's state, in order to pull out certain bits of data for our analytics. 
For example, when viewing an Artist's profile, there's a follow button which, [depending on the state, changes action and appearance](https://github.com/artsy/emission/blob/master/src/lib/Components/Artist/Header.tsx#L129-L141). When pressing this button, we would send the analytics events stating whether the user pressed "follow artist" or "unfollow artist", and this logic is captured in the component's state. 
As such I've added [the …
=> [Feature] Access to component state data

.eslintrc.json, .prettierrc.json, package-lock.json, package.json, src/__tests__/e2e.test.js, src/__tests__/makeClassMemberDecorator.test.js, src/__tests__/trackEventMethodDecorator.test.js, src/__tests__/trackingHoC.test.js, src/__tests__/withTrackingComponentDecorator.test.js, src/index.js, src/makeClassMemberDecorator.js, src/trackEventMethodDecorator.js, src/trackingHoC.js, src/withTrackingComponentDecorator.js
This PR will add [Prettier](https://github.com/prettier/prettier) to this repo. I have set up it up to match the `eslint` configuration that is currently setup. 
Things to note: 
**New File**: `.prettierrc.json`
- This adds the single quote and trailing comma (es5) configuration. This was added because prettier was conflicting with eslint originally 
**Pre-Commit Hook**
- While running `git commit ...` there is a hook to apply prettier to all staged files. This will catch any changes that were added from a contributor who doesn't have prettier in their editor. 
**Minor Changes**
- Once prettier was enabled there where some minor formatting updates to files to follow prettier's rules. They don't conflict with eslints rules
=> Prettier Configuration with Eslint and Pre-Commit Hook

src/__tests__/e2e.test.js, src/withTrackingComponentDecorator.js
#59 
IMHO, you can either compute the tracking data lazily only when tracking is being called or eagerly whenever props changed.
Currently, the tracking data is being computed eagerly in the constructor, so for the minimal code change, i added the same computing call in the `componentWillReceiveProps`
=> Fix issue 59

.gitignore, package-lock.json, package.json, src/withTrackingComponentDecorator.js
Replacing lodash.merge with the deepmerge package significantly reduces bundle size.
https://bundlephobia.com/result?p=react-tracking@5.1.0 (6.3kb gzipped)
https://bundlephobia.com/result?p=@dortzur/react-tracking@5.2.1 (2.7kb gzipped)
Thanks for open sourcing this package by the way.
=> Replace lodash.merge with deepmerge package

README.md
This is mainly to re-direct people to see a bunch of example code if they're using the typedefs, as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27221 is both elegant but a bit tricky to do yourself without a reference.
=> Adds a note about the typedefs for typescript support

README.md, src/__tests__/trackEventMethodDecorator.test.js, src/trackEventMethodDecorator.js
This introduces the ability to use `@track` on asynchronous methods and have the track functionality run *after* the method has resolved:
```js
{
...
@track()
async fireEvent() {
await eventDispatch();
}
}
```
It doesn't change the ability to track non-async methods.
Because the tracked method needs to be run before it can be identified as an asynchronous method (it returns a Promise), this change alters the flow of when the function and tracking are called. In all cases, the function will run *and then* the tracking will be called.
Since this deviates from the original order of operations, I can see how this may introduce unwanted effects. Alternatively, I can see a new `@trackAsync` decorator that could be used for this. I do prefer transparent handling of this kind of thing, and not …
=> Track async method

src/__tests__/dispatchTrackingEvent.test.js, src/dispatchTrackingEvent.js
If you have multiple mount points in your app, or if you only use `react-tracking` in subtrees of your React app, you may encounter a situation where you see empty tracking objects pushed to your data store. That's... not terribly useful.
This change prevents empty objects from being pushed to `window.dataLayer`.
=> Guard against pushing empty events

package-lock.json, package.json
Ugh! one more, and hopefully the last! Sorry this wasn't caught. With `preset-env` and `core-js` importing exactly what's needed `babel-runtime` can be removed.
=> Remove unneeded peerDep

README.md, src/__tests__/trackEventMethodDecorator.test.js, src/trackEventMethodDecorator.js
This change allows us to conditionally track events depending on the return value of the function passed into `@track`. If the function returns `null` or `undefined` then `trackEvent` will not be invoked.
We've patched this in our own version of `react-tracking` in order to only track when a user _unchecks_ a box. Example code is below and can be found [here](https://github.com/artsy/reaction/pull/1459/files#diff-ec0ceeeb68c615892b6b5a053119b0edR143).
```
@track((props, state, args) => {
const willInputBillingAddress = !args[0]
if (willInputBillingAddress) {
return {
action_type: Schema.ActionType.Click,
subject: Schema.Subject.BNMOUseShippingAddress,
flow: "buy now",
type: "checkbox",
}
}
})
handleChangeHideBillingAddress(hideBillingAddress: boolean) {
...
}
```
=> Don't invoke trackEvent when tracking data is null or undefined

package-lock.json, package.json, src/__tests__/e2e.test.js, src/__tests__/withTrackingComponentDecorator.test.js, src/withTrackingComponentDecorator.js
Updates to use new Context API, [React.createContext()](https://reactjs.org/docs/context.html)
After this is published, minimum React will be 16.3
Closes #67
=> new context api

.babelrc, package-lock.json, package.json
(likely a breaking change for core-js@2)
Fixes #119
=> upgrade babel dependencies + config to support core-js@3

README.md, package.json, src/__tests__/e2e.test.js, src/__tests__/useTracking.test.js, src/index.js, src/useTracking.js
Closes https://github.com/nytimes/react-tracking/issues/120
> This is an internal pattern that we're currently rolling out to devs on our team and have yet to use extensively. Wanted to open up a PR for feedback and other suggestions.
This PR adds a new `useTracking` hook now that https://github.com/nytimes/react-tracking/pull/118 has been implemented. 
```jsx
// App.js 
import { track } from 'react-tracking'
import { Child } from './Child'
// Inject a tracking context into the tree
const App = track({
foo: 'bar'
})(props => {
return <Child />
})
```
And then the parent and children can pull it out via `useTracking`
```jsx
import { useTracking } from 'react-tracking'
export const Child = () => {
const tracking = useTracking()  
return <div onClick={() => tracking.trackEvent(...)}>
}
``` …
=> Add new `useTracking` React hook

src/__tests__/e2e.test.js, src/__tests__/withTrackingComponentDecorator.test.js, src/useTracking.js, src/withTrackingComponentDecorator.js
The React 16 context has slightly different behavior when dealing with updates in a subtree. With the legacy context, a `shouldComponentUpdate` returning false in a component tree would cause the context consumers in its subtree to not receive context updates. From the React docs:
> The problem is, if a context value provided by component changes, descendants that use that value won’t update if an intermediate parent returns false from shouldComponentUpdate.
-- https://reactjs.org/docs/legacy-context.html#updating-context
With the new context introduced in React 16, the context consumers will always update regardless of a parent's optimizations:
> All consumers that are descendants of a Provider will re-render whenever the Provider’s value prop changes. The propagation from Provider to …
=> feat(withTrackingComponentDecorator): rewrite context behavior to improve performance

src/__tests__/e2e.test.js, src/__tests__/index.test.js, src/index.js
- Default and named `track` export
- Remove ReactTrackingContext from public exports since it's an implementation detail
=> Massage exports

src/withTrackingComponentDecorator.js
I think this accomplishes the dual purposes of not lying to react about dependencies while also preventing unwanted re-renders. All tests are passing, the linter is happy, and all looks well in the light manual regression testing I've done.
=> Don't lie to react about dependencies

.eslintrc.js, package-lock.json, package.json, src/withTrackingComponentDecorator.js
Figured we should probably pull in [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) since we're making heavy use of them now.
At first I applied the auto-fix for all issues, but that broke one of the e2e tests: `does not cause unnecessary updates due to context changes` -- and that's a critical one for performance reasons. So I had to selectively eslint-disable the `tracking` dependency in the hooks dependency array for a couple of the hooks. Not sure if there's a more idiomatic way around that?
Admittedly, I haven't personally used Hooks too much myself, so I'm definitely keen to hear your feedback on this, @bgergen if you could take a look when you get a chance 🙏
=> Add eslint react hooks plugin

src/__tests__/index.test.js, src/index.js, src/withTrackingComponentDecorator.js
This PR removes `TrackingContextType`, which I believe is leftover from an era when the library used the legacy context API. As far as I can tell it no longer provides any value. I also removed the test that checked for the context type export and replaced it with the same check for the `useTracking` hook.
=> Remove TrackingContextType, test useTracking export

src/__tests__/e2e.test.js, src/__tests__/trackEventMethodDecorator.test.js, src/trackEventMethodDecorator.js
Follow-up to https://github.com/nytimes/react-tracking/pull/147#discussion_r347910419
=> Handle async rejection

README.md, src/__tests__/e2e.test.js, src/__tests__/withTrackingComponentDecorator.test.js, src/withTrackingComponentDecorator.js
Add a `forwardRef` option and fix the tests. Please review.
=> Add forwardRef

src/__tests__/hooks.test.js
An initial PR to introduce some failing tests (skipped) to code against for https://github.com/nytimes/react-tracking/issues/138
=> Failing hooks test to code against

src/__tests__/hooks.test.js
I noticed one of the tests never got updated to the hooks API, plus added another minor test
_NOTE: This PR is going into `expanded-hooks-api` branch._
=> tweak + small new test

src/ReactTrackingContext.js, src/__tests__/e2e.test.js, src/__tests__/hooks.test.js, src/__tests__/useTracking.test.js, src/useTracking.js, src/useTrackingImpl.js, src/withTrackingComponentDecorator.js
This PR could probably use more refinement, but I want to get some early feedback on it. It addresses issue https://github.com/nytimes/react-tracking/issues/138. I spent some time considering this API vs having the `Track` component take in props. I think this is the better option because it allows contextual data to be passed into the hook and get back a `trackEvent` function that can make use of that data, which would not be possible if the data had to be passed into the `Track` component instead.
One minor (I think) concern I still have is that it might be too easy for a developer to forget to wrap their markup in the `Track` component, and mistakenly believe that child components are receiving contextual data when they're not. Open question: Would it make any sense to emulate the …
=> Expand useTracking API to accept contextual data

README.md, package.json
This updates the docs to account for the enhancements to the `useTracking` API introduced in https://github.com/nytimes/react-tracking/commit/9c941ff1581959f8965247d99a921504224b40b0
=> Update docs for expanded useTracking API

package.json
This PR aims to widen the peer dependency range to include React 17
Fixes #180
=> Widen peer dependency range to include React 17

.drone.yml, .travis.yml
This adds a config that runs on every push to all branches. I saw that the old `.travis.yml` file seemed to be running the `prepare` script for 3 node versions, so I did the same for drone (for node 14, 12, and 10). @tizmagik Does this behavior sound right?
=> Add drone config

.drone.yml
I updated the previously-named `master` primary branch to be named `main`. This updates the drone file to properly reference the new branch name.
=> Update drone yml to reference main

README.md
Adding a note to document the bug reported in issue https://github.com/nytimes/react-tracking/issues/189 until we can address.
=> Add options.process caveat to readme

src/useTracking.js, src/useTrackingImpl.js
We're taking advantage of React's [useDebugValue](https://reactjs.org/docs/hooks-reference.html#usedebugvalue) hook here in order to display contextual tracking data when a user inspects the hook in React devtools. 2 open questions:
1. Is there any other data internal to the library that would be useful to display here?
2. ~Is it necessary for us to call this twice? I like having it in the higher-level `useTracking` hook because it makes it more discoverable. Otherwise, devs would need to inspect the nested `useTrackingImpl` hook in order to discover it. I added it also to `useTrackingImpl` because that makes it visible for components that are using the HoC rather than the hook, since that hook is shared between both. It's redundant, but covers both use cases. Def open to thoughts on …
=> Take advantage of useDebugValue to display data in devtools

.husky/pre-commit, package-lock.json, package.json
Upgrade husky to v8 and lint-staged to v13
New Husky:
- Zero dependencies and lightweight (6 kB)
- Powered by modern new Git feature (core.hooksPath)
- Follows npm and Yarn best practices regarding autoinstall
=> chore: upgrade husky@8 and lint-staged@13

package.json, src/__tests__/e2e.test.js
Enhance e2e test suite to run against src as well as the built library. This is especially useful in case we upgrade babel or change any babel settings to ensure the transpilation still works as expected for the built artifact.
=> Enhance e2e test suite

README.md, src/dispatchTrackingEvent.js
This is to improve the compatibility with React Native and ensure the dispatch function is triggered correctly.
Currently, the code assumes the availability of the "window" object without checking its type, which is causing an issue with the dispatch function in React Native where "window" is not present. 🙅‍♂️
To fix this, I have added a simple check to ensure the "window" object is defined using typeof window === "undefined". This allows the code to gracefully handle React Native environments and ensures the dispatch function works smoothly in web browser environments. 🚀
Thank you so much for your time and consideration. 🙏
=> Fix compatibility issue with React Native environment
